#公共配置与profiles选择无关
mybatis:
    mapper-locations: classpath:sql/*.xml
    type-aliases-package: com.chat.web.entity
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/chat
        username: root
        password:
        driver-class-name: com.mysql.jdbc.Driver
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource